unsafeWindow.extPresets = {
  'Mesh': {url: 'https://cdn.rawgit.com/bobbybee/mesh-2.0/master/ext.js', author: 'bobbybee'},
  //'Scratch Cloud': {url: 'https://dl.dropboxusercontent.com/u/6274273/web/scratchcloud/icon.js', author: 'MathWizz'},
  //'Image Stuff': {url: 'http://scratch.cf/extensions/imagestuff.js', author: 'djdolphin'},
  'CookieVars': {url:'https://cdn.rawgit.com/Felizolinha/7b7aec74cec298a68f46/raw/0652fd6a200ef4005e8b21d8df32fb96d823f83d/CookieVars', author: 'djdolphin'},
  'Cool helpful things extension': {url: 'https://cdn.rawgit.com/uyjulian/f984c9111b508a48bdf18308f0ad5932/raw/7a11fc68f93f826a1e6640b5946184a5ff79036f/Cool%2520helpful%2520things%2520extension.js', author: 'PullJosh'},
  'More Math': {url: 'https://savakamyimages00000.weebly.com/uploads/6/4/5/3/6453739/more_math.js', author: 'savaka'},
  'Javascript Dialogs': {url: 'https://savakamyimages00000.weebly.com/uploads/6/4/5/3/6453739/javascript_dialogs.js', author: 'savaka'},
  'Link Opener': {url: 'https://savakamyimages00000.weebly.com/uploads/6/4/5/3/6453739/link_opener.js', author: 'savaka'},
  'littleBits': {url: 'https://cdn.rawgit.com/khanning/scratch-littlebits-extension/gh-pages/littlebits_extension.js', author: 'khanning'},
  //'Data Blocks': {url: 'https://cdn.rawgit.com/Thepuzzlegame/My-Scratch-Extensions/master/data_extension.js', author: 'Thepuzzlegame'},
  //'Infinity Reporter': {url: 'https://cdn.rawgit.com/Thepuzzlegame/My-Scratch-Extensions/master/infinity_reporter.js', author: 'Thepuzzlegame'},
  //'Extension Loader': {url: 'https://cdn.rawgit.com/Thepuzzlegame/My-Scratch-Extensions/master/extension_loader.js', author: 'Thepuzzlegame'},
  'Alarm extension': {url: 'https://cdn.rawgit.com/LLK/scratchx/master/alarm_extension.js', author: 'sdg1'},
  'Browser Stuff': {url: 'https://cdn.rawgit.com/LLK/scratchx/master/browser_extension.js', author: 'grokblah'},
  'Joystick': {url: 'https://cdn.rawgit.com/LLK/scratchx/master/joystickExtension.js', author: 'sdg1'},
  'Local Storage': {url: 'https://cdn.rawgit.com/LLK/scratchx/master/localstorage_extension.js', author: 'sdg1'},
  'PicoBoard': {url: 'https://cdn.rawgit.com/LLK/scratchx/master/picoExtension.js', author: 'grokblah'},
  'PicoBoard Fixed': {url: 'https://cdn.rawgit.com/uyjulian/f6e9bbc8f7492ff6888dab15f1de9138/raw/922f44d0a81042804f146b85733c787e6250dc75/PicoBoard%2520Fixed.js', 'author': 'SCRAXE'},
  'Power Extension': {url: 'https://cdn.rawgit.com/LLK/scratchx/master/power_extension.js', author: 'sdg1'},
  'Random wait extension': {url: 'https://cdn.rawgit.com/LLK/scratchx/master/random_wait_extension.js', author: 'sdg1'},
  'Speech to Text': {url: 'https://cdn.rawgit.com/LLK/scratchx/master/speech_to_text_extension.js', author: 'sdg1'},
  'Text to Speech': {url: 'https://cdn.rawgit.com/LLK/scratchx/master/text_to_speech_extension.js', author: 'sdg1'},
  'Text to Speech Simple': {url: 'https://cdn.rawgit.com/LLK/scratchx/master/text_to_speech_simple_extension.js', author: 'sdg1'},
  'Weather Extension': {url: 'https://cdn.rawgit.com/LLK/scratchx/master/weather_extension.js', author: 'sdg1'},
  //'ScratchExt': {url: 'http://stefanbates.com/library/install.js', author: 'GrannyCookies, Yoda3D, Thistleeverfreen'},
  'Browser Info and Language': {url: 'https://andrewjcole.weebly.com/uploads/8/0/9/8/8098232/browser-info-and-language.js', author: 'andrewjcole'}
};
//Thanks, Thepuzzlegame and djdolphin!
